#ServerListPingEvent related stuff goes here
ping:
  motd: "&6Your favourite minecraft server!/n&3There are &b&lbees" #Color Codes with '&' can be used. Use "/n" for a line break.
  image: "server-icon.png" #Images have to be in the folder "icons"
join:
  title: "0815Craft"
  subtitle: "Have fun on the best server!"
tnt:
  enabledworlds: #Add here names of the worlds you want to enable tnt in.
    - "world"
    - "world_the_end"
    - "world_nether"
tablist:
  header: "Your favourite minecraft server! /n Now 1.15.2"
  footer: "Join us on teamspeak/nts.myserver.com"
command:
  teamspeak: "Join our teamspeak server at ts.craftersforever.de"
  discord: "Join our Discord now. https://discord.gg/"
  vote: "Vote now for our server on https://serverlist.mc/vote/0815Craft"
trello:
  key: your API KEY
  token: Your API token
  listID: ID of List the card should be in
vote:
  broadcast: The good lad %player% has voted for CraftersForever and received a reward!
  thank: Thank you for voting for the server! Here is a little reward for you %player%!
  rewards:
    - "minecraft:give %player% minecraft:diamond 1"
    - "crate give %player% key"